version: '3.7'
services:
  nginx:
    image: nginx:1.17.2-alpine
    ports:
      - '8080:80'
    volumes:
      - ./webapp:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - pgsql
      - redis
  php:
    build: ./php
    user: '1000:1000'
    volumes:
      - ./webapp:/var/www/html
      - ./php/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./php/php.ini-production:/usr/local/etc/php/php.ini-production
      - ./php/docker-php-ext-sodium.ini:/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
  pgsql:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prueba
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata
    ports:
      - 54324:5432
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
